server:
  port: 8080
spring:
  datasource:
  url: jdbc:mysql://localhost/pantograph?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.example.demo.*.model
  mapper-locations: classpath:mapping/*/*.xml

thymeleaf:
  prefix: classpath:/templates/    #指定资源位置
  mode: LEGACYHTML5

logging:
  config: logback-spring.xml